ansible_connection: network_cli
ansible_network_os: eos
ansible_user: admin
ansible_ssh_pass: admin

hostname: r2

interfaces:
  - name: lo0
    description: Loopback
    ip: 2.2.2.2/32
  - name: e1
    description: link1
    ip: 192.168.101.2/30
    ospf_area: 0
    ospf_cost: 1
  - name: e2
    description: link2
    ip: 192.168.102.2/30
    ospf_area: 1
    ospf_cost: 1
  - name: e3
    description: host2
    ip: 192.168.2.254/24
